config/routes.rb
KandyApp::Application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  devise_scope :user do
    namespace :users do
      scope 'manage' do
        controller :manage do
          get '/' => :index, as: 'manage'
          get '/edit/:id' => :edit, as: 'manage_edit'
          post '/edit/:id' => :update
          delete '/edit/:id' => :destroy
        end
      end
    end
  end

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  controller :home do
    get 'error' => :error
  end

  namespace :webhooks do
    scope 'sms' do
      controller :sms do
        post 'order-creation' => :order_creation
        post 'order-update' => :order_update
        post 'order-payment' => :order_payment
        # post 'order-fulfillment' => :order_fulfillment
        post 'customer-creation' => :customer_creation
      end
    end
    controller :shop do
      post 'shop/update' => :update
      end
    controller :uninstalled do
      post 'app/uninstalled' => :index
    end
  end

  scope 'preferences' do
    controller :preferences do
      get '/' => :index, as: :preferences
      get 'api-keys' => :api_keys, as: 'api_keys'
      get 'sms-alert-templates' => :sms_alert_templates, as: 'sms_alert_templates'
      get 'chat-box-widget' => :chat_box_widget, as: 'chat_box_widget'
      get 'chat-box-widget-preview' => :chat_box_widget_preview, as: 'chat_box_widget_preview'
      post '/' => :update
    end
    controller :transcripts do
      get '/transcripts' => :index, as: 'chat_transcripts'
      get '/transcripts/:id' => :view, as: 'chat_transcript'
      delete 'transcripts' => :destroy
      match 'transcripts' => :archive, via: [:put, :patch]
    end
    controller :reports do
      get '/reports' => :index
    end
  end

  scope 'help' do
    controller :help do
      get 'variables' => :variables
    end
  end

  scope 'chat' do
    controller :chat do
      post 'widget' => :widget, as: 'chat_widget'
      get 'online' => :check, as: 'chat_check_online'
      post 'online' => :ping, as: 'chat_ping_online'
      post 'change-user-status' => :change_user_status, as: 'change_user_status'
      post 'request' => :request_chat, as: 'chat_request'
      post 'join' => :join_chat, as: 'chat_join'
      post 'leave' => :leave_chat, as: 'chat_leave'
      post 'close' => :close_chat, as: 'chat_close'
      post 'save' => :save_message, as: 'chat_save'
      post 'rating' => :rating, as: 'chat_rating'
      get 'load' => :load_chat, as: 'chat_load'
      post 'send-mail' => :send_mail, as: 'chat_send_mail'
      post 'send-mail-transcript' => :send_mail_transcript, as: 'chat_send_mail_transcript'
      get 'download' => :download, as: 'chat_download'
      delete 'ban' => :ban, as: 'chat_ban'
    end
  end

  scope 'app' do
    controller :shopify do
      get 'script-tags' => :script_tags
    end
    scope 'installed' do
      controller :installed do
        get '/' => :index, as: 'app_installed'
        post 'kandy_account' => :set_kandy_account, as: 'app_installed_kandy_account'
        post 'admin_account' => :set_admin_account, as: 'app_installed_admin_account'
      end
    end
  end

  root :to => 'home#index'
end

app/controllers/installed_controller.rb
class InstalledController < ApplicationController
  layout 'embedded_app'
  skip_before_filter :verify_authenticity_token
  before_action :load_shop

  # GET /app/installed
  def index
    if @shop.initialized
      redirect_to root_url
    else
      # if app is initialized but it is uninstalled from shop, ...
      if @shop.users.size > 0
        update_shop_details # ...get shop details
        @shop.save

        # ...and update webhooks and script tags
        setup_webhooks
        setup_script_tags

        redirect_to session['return_url'] || root_url and return
      end
    end

    session[:step] ||= 0

    if params[:step] == '2' && session[:step] == 1
      @kandy_users = @shop.kandy_users.all
      render 'admin_account'
    else
      if params[:step] == '3' && session[:step] == 2
        redirect_to root_url
      end
    end
  end

  # POST /app/installed/kandy_account
  def set_kandy_account
    if @shop.update_attributes(shop_params)
      kandy = Kandy.new(domain_api_key: @shop.kandy_api_key, domain_api_secret: @shop.kandy_api_secret)
      users = kandy.domain_users
      if users.blank? || users.size < 1
        flash[:error] = 'Your kandy account should have least 1 user.'
      else
        # save all kandy users to database
        users.each do |u|
          @shop.kandy_users.create(username: u.user_id, email: u.user_email, password: u.user_password,
                                   first_name: u.user_first_name, last_name: u.user_last_name, phone_number: u.user_phone_number,
                                   api_key: u.user_api_key, api_secret: u.user_api_secret, country_code: u.user_country_code, domain_name: u.domain_name)
          # save domain access token for next usages
          @shop.kandy_domain_access_token = kandy.domain_access_token
          @shop.save
        end
        session[:step] = 1
        redirect_to action: :index, step: 2 and return
      end
      render :index
    end
  end

  # POST /app/installed/admin_account
  def set_admin_account
    user = @shop.users.create(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation],
                              first_name: params[:first_name], last_name: params[:last_name], role: User::ADMIN,
                              phone_number: params[:phone_number], invitation_accepted_at: Time.now.utc)
    if user.persisted?
      # create new admin user and setup shopify
      @kandy_user = @shop.kandy_users.find(params[:kandy_user_id])
      @shop.template = Template.new
      @shop.widget = Widget.new
      @kandy_user.user = user
      update_shop_details

      @shop.save
      @kandy_user.save

      setup_webhooks
      setup_script_tags

      redirect_to session['return_url'] || root_url and return
    else
      flash[:error] = user.errors.full_messages[0]
    end

    @kandy_users = @shop.kandy_users.all
    render 'admin_account'
  end

  private

  # get shop owner details (timezone, email and phone number)
  def update_shop_details
    @shop.initialized = true
    @shop_details = ShopifyAPI::Shop.current
    @shop.time_zone = @shop_details.timezone.match(/\(.*\) (.*)/)[1]
    @shop.email = @shop_details.email
    @shop.phone = @shop_details.phone
  end

  # create some webhooks
  def setup_webhooks
    begin
      webhooks = ShopifyAPI::Webhook.find :all
      webhooks.each do |webhook| # remove old webhooks
        webhook.destroy if webhook.address.include?(root_url)
      end
      [
          {url: webhooks_app_uninstalled_url, topic: 'app/uninstalled'},
          {url: webhooks_order_creation_url, topic: 'orders/create'},
          {url: webhooks_order_update_url, topic: 'orders/updated'},
          {url: webhooks_order_payment_url, topic: 'orders/paid'},
          {url: webhooks_customer_creation_url, topic: 'customers/create'},
          {url: webhooks_shop_update_url, topic: 'shop/update'}
      ].each do |webhook|
        ShopifyAPI::Webhook.create(address: webhook[:url], topic: webhook[:topic], format: 'json')
      end

    rescue => ex
      puts ex.message
    end
  end

  # add a script tags to load widget on pageload
  def setup_script_tags
    begin
      tags = ShopifyAPI::ScriptTag.find :all
      tags.each do |tag| # remove old script tags
        tag.destroy if tag.src.include?(root_url)
      end
      [script_tags_url].each do |tag|
        ShopifyAPI::ScriptTag.create(src: tag, event: 'onload')
      end
    rescue => ex
      puts ex.message
    end
  end

  def shop_params
    params.require(:shop).permit(:id, :kandy_api_key, :kandy_api_secret)
  end

  def load_shop
    @shop = Shop.find_by_shopify_domain(@shop_session.url)
  end

end

app/views/installed/admin_account.haml
:coffeescript
  window.mainPageTitle = 'Setup (2/2)'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      buttons:
        primary:
          label: 'Finish'
          message: 'save-form-message'
    ShopifyApp.Bar.loadingOff()

= form_tag app_installed_admin_account_path, method: :post, 'data-shopify-app-submit': 'save-form-message' do
  = hidden_field_tag :step, '2'
  .row
    .col-sm-3
      %h5 Admin account
    .col-sm-9.panel
      .panel-body
        .row.form-group
          .col-sm-6
            = label_tag :first_name, 'First name'
            = text_field_tag :first_name, params[:first_name], class: 'form-control'
          .col-sm-6
            = label_tag :last_name, 'Last name'
            = text_field_tag :last_name, params[:last_name], class: 'form-control'
        .row.form-group
          .col-sm-12
            = label_tag :phone_number, 'Phone number'
            = text_field_tag :phone_number, params[:phone_number], class: 'form-control input-sm'
        .row.form-group
          .col-sm-12
            = label_tag :email, 'Email'
            %abbr{title: 'required'} *
            = email_field_tag :email, params[:email], autofocus: true,  class: 'form-control input-sm'
        .row.form-group
          .col-sm-12
            = label_tag :password, 'Password'
            %abbr{title: 'required'} *
            = password_field_tag :password, '', class: 'form-control input-sm'
        .row.form-group
          .col-sm-12
            = label_tag :password_confirmation, 'Password Confirmation'
            %abbr{title: 'required'} *
            = password_field_tag :password_confirmation, '', class: 'form-control input-sm'
        .row.form-group
          .col-sm-12
            = label_tag :kandy_user_id, 'Kandy user'
            %abbr{title: 'required'} *
            = select_tag :kandy_user_id, options_from_collection_for_select(@kandy_users, :id, :username), {class: 'select2 form-control'}

app/views/installed/index.haml
:coffeescript
  window.mainPageTitle = 'Setup (1/2)'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      buttons:
        primary:
          label: 'Next'
          message: 'save-form-message'
    ShopifyApp.Bar.loadingOff()

= form_for @shop, url: app_installed_kandy_account_path, method: :post, html: {'data-shopify-app-submit': 'save-form-message'} do |f|
  .row
    .col-sm-3
      %h5 Kandy Domain Keys
      %span.help-block
        If you don't have a Kandy account, please
        %a{href: 'https://developer.kandy.io/'} register
        with Kandy to start.
    .col-sm-9.panel
      .panel-body
        .form-group
          = f.label :kandy_api_key, 'Domain Key'
          %abbr{title: 'required'} *
          = f.text_field :kandy_api_key, class: 'form-control input-sm', placeholder: 'DAK24d0f137128846f8ba12204f3502****'
        .form-group
          = f.label :kandy_api_secret, 'Domain Secret Key'
          %abbr{title: 'required'} *
          = f.text_field :kandy_api_secret, class: 'form-control input-sm', placeholder: 'DAS7828b8cda2c04335923311b97284****'