config/routes.rb
KandyApp::Application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  devise_scope :user do
    namespace :users do
      scope 'manage' do
        controller :manage do
          get '/' => :index, as: 'manage'
          get '/edit/:id' => :edit, as: 'manage_edit'
          post '/edit/:id' => :update
          delete '/edit/:id' => :destroy
        end
      end
    end
  end

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  controller :home do
    get 'error' => :error
  end

  namespace :webhooks do
    scope 'sms' do
      controller :sms do
        post 'order-creation' => :order_creation
        post 'order-update' => :order_update
        post 'order-payment' => :order_payment
        # post 'order-fulfillment' => :order_fulfillment
        post 'customer-creation' => :customer_creation
      end
    end
    controller :shop do
      post 'shop/update' => :update
      end
    controller :uninstalled do
      post 'app/uninstalled' => :index
    end
  end

  scope 'preferences' do
    controller :preferences do
      get '/' => :index, as: :preferences
      get 'api-keys' => :api_keys, as: 'api_keys'
      get 'sms-alert-templates' => :sms_alert_templates, as: 'sms_alert_templates'
      get 'chat-box-widget' => :chat_box_widget, as: 'chat_box_widget'
      get 'chat-box-widget-preview' => :chat_box_widget_preview, as: 'chat_box_widget_preview'
      post '/' => :update
    end
    controller :transcripts do
      get '/transcripts' => :index, as: 'chat_transcripts'
      get '/transcripts/:id' => :view, as: 'chat_transcript'
      delete 'transcripts' => :destroy
      match 'transcripts' => :archive, via: [:put, :patch]
    end
    controller :reports do
      get '/reports' => :index
    end
  end

  scope 'help' do
    controller :help do
      get 'variables' => :variables
    end
  end

  scope 'chat' do
    controller :chat do
      post 'widget' => :widget, as: 'chat_widget'
      get 'online' => :check, as: 'chat_check_online'
      post 'online' => :ping, as: 'chat_ping_online'
      post 'change-user-status' => :change_user_status, as: 'change_user_status'
      post 'request' => :request_chat, as: 'chat_request'
      post 'join' => :join_chat, as: 'chat_join'
      post 'leave' => :leave_chat, as: 'chat_leave'
      post 'close' => :close_chat, as: 'chat_close'
      post 'save' => :save_message, as: 'chat_save'
      post 'rating' => :rating, as: 'chat_rating'
      get 'load' => :load_chat, as: 'chat_load'
      post 'send-mail' => :send_mail, as: 'chat_send_mail'
      post 'send-mail-transcript' => :send_mail_transcript, as: 'chat_send_mail_transcript'
      get 'download' => :download, as: 'chat_download'
      delete 'ban' => :ban, as: 'chat_ban'
    end
  end

  scope 'app' do
    controller :shopify do
      get 'script-tags' => :script_tags
    end
    scope 'installed' do
      controller :installed do
        get '/' => :index, as: 'app_installed'
        post 'kandy_account' => :set_kandy_account, as: 'app_installed_kandy_account'
        post 'admin_account' => :set_admin_account, as: 'app_installed_admin_account'
      end
    end
  end

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  # GET /
  def index
    authorize! :chat, :all

    @shop = Shop.find_by_shopify_domain(@shop_session.url)

    # check kandy users empty?
    if current_user.kandy_user.blank?
      if current_user.admin?
        flash[:error] = 'Please setup kandy user for your account.'
        redirect_to users_manage_edit_path(current_user) and return
      else
        flash[:error] = 'Please contact admin to setup kandy user for your account.'
        sign_out(current_user)
        redirect_to new_user_session_path and return
      end
    else if current_user.kandy_user.password.blank?
           kandy = Kandy.new(domain_api_key: @shop.kandy_api_key, domain_api_secret: @shop.kandy_api_secret)
           current_user.kandy_user.access_token = kandy.user_access_token(username: current_user.kandy_user.username)
         end
    end
  end
end

app/views/home/help.haml
:coffeescript
  window.mainPageTitle = 'Help Page'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      buttons:
        secondary:
          label: 'Back'
          href: '/'
          target: 'app'
    ShopifyApp.Bar.loadingOff()

%h2 Hey! This is the help page.

app/views/home/index.haml
%script{src: asset_url('kandy-chatbox-dashboard.js')}
%script{:src => '//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry'}
%script{:src => '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'}

:coffeescript
  window.mainPageTitle = 'Dashboard'
  window.kandyVideoCallEnabled = #{ENV['KANDY_VIDEO_CALL_ENABLED']}

  displayLoadingOverlay()

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      buttons:
        primary:
          label: 'Preferences'
          href: "#{preferences_url}"
          target: 'new'
        secondary: [
          {label: 'Kandy.IO', href: 'http://kandy.io/', target: 'new'}
          {label: 'Logout', message: 'logout-form-message'}
        ]

    kandy.setup
      #remoteVideoContainer: $('.incoming-video')
      #localVideoContainer: $('.outgoing-video')
      listeners:
        message: handleEventListeners
        callinitiated: onCallInitiate
        callinitiatefailed: onCallInitiateFail
        oncall: onCall
        callended: onCallTerminate

        callincoming: onCallIncoming
        callanswered: onCallAnswer
        callrejected: onCallRejected

    if "#{current_user.kandy_user.password}" is ""
      kandy.loginSSO "#{current_user.kandy_user.access_token}", (msg) ->
        loadAndStartChat('#{chat_load_url}')
      , (e) ->
        ShopifyApp.flashError("Error occurred while connecting to Kandy server. Press F5 to refresh.")
        console.log e
    else
      kandy.login "#{@shop.kandy_api_key}", "#{current_user.kandy_user.username}", "#{current_user.kandy_user.password}", (msg) ->
        loadAndStartChat('#{chat_load_url}')
      , (e) ->
        ShopifyApp.flashError("Error occurred while connecting to Kandy server. Press F5 to refresh.")
        console.log e

.row
  .col-sm-3.col-xs-12
    .row
      .panel.panel-default
        .panel-heading
          .pull-right
            %button#user-status-btn.btn.btn-xs.btn-warning.hide{'data-toggle': 'tooltip', 'data-placement': 'bottom'} Unavailable
          %i.fa.fa-comment
          Incoming Chats
        .panel-body
          .list-group#conversations-list
    .row
      .panel.panel-default
        .panel-heading
          %i.fa.fa-commenting
          Other Active Chats
        .panel-body
          .list-group#other-active-conversations-list
    .row
      .panel.panel-default
        .panel-heading
          %i.fa.fa-users
          Operators
        .panel-body
          .list-group#users-online-list

  .col-sm-9.col-xs-12
    .row#conversations-dashboard{style: 'display: none;'}
      .col-md-8
        .panel.panel-default
          .panel-body
            %ul#conversation-tabs.nav.nav-tabs{role: 'tablist'}
            .tab-content#conversation-tabs-content
      .col-md-4
        .row
          .panel.panel-default
            .panel-heading
              %i.fa.fa-info
              Details
            .panel-body
              .pad-left.pad-right
                #conversation-detail
        .row
          .panel.panel-default
            .panel-heading
              %i.fa.fa-history
              Chat history
            .panel-body
              #conversation-history
                .text-center
                  \...
        .row
          .panel.panel-default
            .panel-heading
              %i.fa.fa-location-arrow
              Location
            .panel-body
              #conversation-location{style: 'width: 100%; height: 250px'}
    .row#welcome-dashboard
      .panel-body
        %h3= "Hey #{current_user.display_name}"
= form_tag destroy_user_session_path, method: :delete, class: 'hide', 'data-shopify-app-submit': 'logout-form-message'