config/routes.rb
KandyApp::Application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  devise_scope :user do
    namespace :users do
      scope 'manage' do
        controller :manage do
          get '/' => :index, as: 'manage'
          get '/edit/:id' => :edit, as: 'manage_edit'
          post '/edit/:id' => :update
          delete '/edit/:id' => :destroy
        end
      end
    end
  end

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  controller :home do
    get 'error' => :error
  end

  namespace :webhooks do
    scope 'sms' do
      controller :sms do
        post 'order-creation' => :order_creation
        post 'order-update' => :order_update
        post 'order-payment' => :order_payment
        # post 'order-fulfillment' => :order_fulfillment
        post 'customer-creation' => :customer_creation
      end
    end
    controller :shop do
      post 'shop/update' => :update
      end
    controller :uninstalled do
      post 'app/uninstalled' => :index
    end
  end

  scope 'preferences' do
    controller :preferences do
      get '/' => :index, as: :preferences
      get 'api-keys' => :api_keys, as: 'api_keys'
      get 'sms-alert-templates' => :sms_alert_templates, as: 'sms_alert_templates'
      get 'chat-box-widget' => :chat_box_widget, as: 'chat_box_widget'
      get 'chat-box-widget-preview' => :chat_box_widget_preview, as: 'chat_box_widget_preview'
      post '/' => :update
    end
    controller :transcripts do
      get '/transcripts' => :index, as: 'chat_transcripts'
      get '/transcripts/:id' => :view, as: 'chat_transcript'
      delete 'transcripts' => :destroy
      match 'transcripts' => :archive, via: [:put, :patch]
    end
    controller :reports do
      get '/reports' => :index
    end
  end

  scope 'help' do
    controller :help do
      get 'variables' => :variables
    end
  end

  scope 'chat' do
    controller :chat do
      post 'widget' => :widget, as: 'chat_widget'
      get 'online' => :check, as: 'chat_check_online'
      post 'online' => :ping, as: 'chat_ping_online'
      post 'change-user-status' => :change_user_status, as: 'change_user_status'
      post 'request' => :request_chat, as: 'chat_request'
      post 'join' => :join_chat, as: 'chat_join'
      post 'leave' => :leave_chat, as: 'chat_leave'
      post 'close' => :close_chat, as: 'chat_close'
      post 'save' => :save_message, as: 'chat_save'
      post 'rating' => :rating, as: 'chat_rating'
      get 'load' => :load_chat, as: 'chat_load'
      post 'send-mail' => :send_mail, as: 'chat_send_mail'
      post 'send-mail-transcript' => :send_mail_transcript, as: 'chat_send_mail_transcript'
      get 'download' => :download, as: 'chat_download'
      delete 'ban' => :ban, as: 'chat_ban'
    end
  end

  scope 'app' do
    controller :shopify do
      get 'script-tags' => :script_tags
    end
    scope 'installed' do
      controller :installed do
        get '/' => :index, as: 'app_installed'
        post 'kandy_account' => :set_kandy_account, as: 'app_installed_kandy_account'
        post 'admin_account' => :set_admin_account, as: 'app_installed_admin_account'
      end
    end
  end

  root :to => 'home#index'
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_shop, except: [:index, :update]

  # GET /preferences
  def index
  end

  # POST /preferences
  def update
    # check permissions
    authorize! :update, :api_key unless params[:shop][:kandy_api_key].blank?
    authorize! :update, :widget unless params[:shop][:widget_attributes].blank?
    authorize! :update, :template unless params[:shop][:template_attributes].blank?

    @shop = Shop.find(params[:shop][:id])
    if params[:shop][:kandy_api_key] == nil && params[:shop][:kandy_api_secret] == nil
      # update preferences except api keys
      if @shop.update_attributes(shop_params)
        flash[:notice] = 'Updated successful'
      else
        flash[:error] = @shop.errors.full_messages.first
      end
    else # update api keys
      if !params[:shop][:kandy_api_key].blank? || !params[:shop][:kandy_api_secret].blank?
        old_api_key = @shop.kandy_api_key
        old_api_secret = @shop.kandy_api_secret

        if old_api_key != params[:shop][:kandy_api_key] || old_api_secret != params[:shop][:kandy_api_secret]
          # Only update keys when api keys is different
          kandy = Kandy.new(domain_api_key: params[:shop][:kandy_api_key], domain_api_secret: params[:shop][:kandy_api_secret])
          users = kandy.domain_users

          if users.blank? || users.size < 1
            flash[:error] = 'Your kandy account should have least 1 users.'
          else
            # delete all current kandy users and save new kandy users
            if @shop.update_attributes(shop_params)
              @shop.kandy_users.destroy_all
              users.each do |u|
                @shop.kandy_users.create(username: u.user_id, email: u.user_email, password: u.user_password,
                                         first_name: u.user_first_name, last_name: u.user_last_name, phone_number: u.user_phone_number,
                                         api_key: u.user_api_key, api_secret: u.user_api_secret, country_code: u.user_country_code, domain_name: u.domain_name)
              end

              flash[:notice] = 'Please setup kandy user for your account and other accounts.'
              redirect_to users_manage_edit_path(current_user) and return
            else
              flash[:error] = @shop.errors.full_messages.first
            end
          end
        end
      else
        flash[:error] = 'Please enter valid kandy api keys.'
      end
    end

    redirect_to params[:back_url] and return
  end

  # GET /preferences/api-keys
  def api_keys
    authorize! :update, :api_key
  end

  # GET /preferences/sms-alert-templates
  def sms_alert_templates
    authorize! :update, :template
  end

  # GET /preferences/chat-box-widget
  def chat_box_widget
    authorize! :update, :widget
  end

  # GET /preferences/chat-box-widget-preview
  def chat_box_widget_preview
    authorize! :update, :widget

    @shop = Shop.find_by_shopify_domain(@shop_session.url)
    render layout: 'application'
  end

  private

  def load_shop
    @shop = Shop.find_by_shopify_domain(params[:shop] || @shop_session.url)
  end

  def shop_params
    params.require(:shop).permit(:id, :kandy_api_key, :kandy_api_secret, :kandy_username, :kandy_password, :kandy_username_guest, :kandy_password_guest,
                                 template_attributes: [:id, :order_creation, :order_update, :order_payment, :customer_creation],
                                 widget_attributes: [:id, :name, :enabled, :color,
                                                     json_string: [
                                                         collapse: [:title, :position, :type, :image, :custom_image_url, :horizontal, :vertical, :scale, :image_in_front_of_tab, :page_load, :show_widget_hide_button],
                                                         start_chat: [:title, :intro_text, :request_button, :ask_for_name, :ask_for_name_text, :ask_for_email, :ask_for_email_text, :ask_for_question, :ask_for_question_text, :ask_for_department],
                                                         no_operators: [:title, :action, :message, :central_email, :email_intro, :name, :email, :question, :email_sent_text, :send_button],
                                                         in_chat: [:title, :message, :no_operators, :greeting, :connecting, :typing, :joined_chat, :left_chat, :closed_chat, :start_message, :send_message],
                                                         chat_close: [:title, :chat_closed, :download, :downloadable, :ask_for_rating, :rating_thanks],
                                                         error_messages: [:name_required, :email_valid, :no_operator_required]
                                                     ]])
  end
end

app/views/preferences/api_keys.haml
:coffeescript
  window.mainPageTitle = 'API Keys'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      breadcrumb:
          label: 'Preferences'
          href: "#{preferences_path}"
          target: 'app'
      buttons:
        primary:
          label: 'Update'
          message: 'save-preferences-form-message'
        secondary:[
          label: 'Back', href: "#{preferences_path}", target: 'app'
        ]
    ShopifyApp.Bar.loadingOff()

= form_for @shop, url: preferences_path, method: :post, html: {'data-shopify-app-submit': 'save-preferences-form-message'} do |f|
  = f.hidden_field :id
  = hidden_field_tag :back_url, api_keys_path
  .row
    .col-sm-3
      %h5 Kandy Domain Key
      %span.help-block
        If you haven’t already registered with your app with Kandy, you should
        %a{href: 'https://developer.kandy.io/', target: '_blank'} register
        with Kandy to start.
      %span.help-block
        %b Notice:
        This action will re-sync all kandy users and you have to map from kandy users to operators again!
    .col-sm-9.panel
      .panel-body
        .form-group
          = f.label :kandy_api_key, 'Domain Key'
          %abbr{title: 'required'} *
          = f.text_field :kandy_api_key, class: 'form-control input-sm', placeholder: 'DAK24d0f137128846f8ba12204f3502****'
        .form-group
          = f.label :kandy_api_secret, 'Domain Secret Key'
          %abbr{title: 'required'} *
          = f.text_field :kandy_api_secret, class: 'form-control input-sm', placeholder: 'DAS7828b8cda2c04335923311b97284****'

app/views/preferences/chat_box_widget_preview.haml
:coffeescript

  window.updateWidget = (config) ->
    KcWidget.update(config)

  done = false

  script = document.createElement('script')
  script.async = true
  script.type = 'text/javascript'
  script.src = '#{asset_url('kandy-chatbox-preview.js')}'
  document.getElementsByTagName('HEAD').item(0).appendChild(script)

  style = document.createElement('link')
  style.rel = 'stylesheet'
  style.href = '#{asset_url('kandy-chatbox.css')}'
  style.type = 'text/css'
  document.getElementsByTagName('HEAD').item(0).appendChild(style)

  widgetConfig = #{raw @shop.widget.json_string.to_json}
  if widgetConfig is null then widgetConfig = {}
  widgetConfig.color = '#{@shop.widget.color}'
  widgetConfig.enabled = #{raw @shop.widget.enabled}
  widgetConfig.current_tab = 'collapsed'

  script.onreadystatechange = script.onload = (e) ->
    if (widgetConfig.enabled && !done && (!this.readyState || this.readyState is 'loaded' || this.readyState is 'complete'))
      window.KcWidget = new window.KCWidget
        config: widgetConfig
      window.parent.triggerFrameLoaded()
      done = true

app/views/preferences/index.haml
:coffeescript
  window.mainPageTitle = 'Preferences'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      buttons:
        secondary:[
          label: 'Dashboard', href: '/', target: 'app'
        ]
    ShopifyApp.Bar.loadingOff()

.pad-left.pad-right
  - if (can? :update, :api_key) || (can? :update, :profile)
    .row
      .panel
        .panel-body
          .col-sm-offset-1
            - if can? :update, :api_key
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-key.fa-3x
                    .col-xs-9
                      %a{href: api_keys_path}
                        %h3.font-bold API Keys
            - if can? :update, :profile
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-user.fa-3x
                    .col-xs-9
                      %a{href: edit_user_registration_path}
                        %h3.font-bold Profile
  - if (can? :update, :widget) || (can? :read, :transcript) || (can? :manage, :user) || (can? :read, :report)
    .row
      .panel
        .panel-body
          .col-sm-offset-1
            - if can? :update, :widget
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-comments.fa-3x
                    .col-xs-9
                      %a{href: chat_box_widget_path}
                        %h3.font-bold Chat Widget
            - if can? :read, :transcript
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-file-text.fa-3x
                    .col-xs-9
                      %a{href: chat_transcripts_path}
                        %h3.font-bold Transcripts
            - if can? :manage, :user
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-users.fa-3x
                    .col-xs-9
                      %a{href: users_manage_path}
                        %h3.font-bold Manage Users
            - if can? :read, :report
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-pie-chart.fa-3x
                    .col-xs-9
                      %a{href: reports_path}
                        %h3.font-bold Reports
  - if can? :update, :template
    .row
      .panel
        .panel-body
          .col-sm-offset-1
            - if can? :update, :template
              .col-sm-6
                .widget.style1
                  .row.vertical-align
                    .col-xs-3
                      %i.fa.fa-send.fa-3x
                    .col-xs-9
                      %a{href: sms_alert_templates_path}
                        %h3.font-bold SMS Notifications
            .col-sm-6.hide
              .widget.style1
                .row.vertical-align
                  .col-xs-3
                    %i.fa.fa-phone.fa-3x
                  .col-xs-9
                    %a{href: '#'}
                      %h3.font-bold Kandy Call

app/views/preferences/sms_alert_templates.haml
:coffeescript
  window.mainPageTitle = 'SMS Alert Templates'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      breadcrumb:
          label: 'Preferences'
          href: "#{preferences_path}"
          target: 'app'
      buttons:
        primary:
          label: 'Save'
          message: 'save-preferences-form-message'
        secondary: [
          label: 'Back', href: "#{preferences_path}", target: 'app'
        ]
    ShopifyApp.Bar.loadingOff()

= form_for @shop, url: preferences_path, method: :post, html: {'data-shopify-app-submit': 'save-preferences-form-message'} do |f|
  = f.hidden_field :id
  = hidden_field_tag :back_url, sms_alert_templates_path
  .row
    .col-sm-3
      %h5 SMS templates
      %span.help-block
        You must have
        %a{href: '#', onclick: 'ShopifyApp.redirect("/settings/general")'}
          %u a valid phone number
        to active this feature.
      %span.help-block
        We use
        %a{href: 'https://github.com/Shopify/liquid/wiki/Liquid-for-Designers', target: '_blank'}
          %u Liquid Templating language
        to render templates.
      %span.help-block
        %a{href: '#', onclick: "newModal('#{variables_url}', 'Template variables')"}
          %u View a list of variables you can use.
    .col-sm-9.panel
      .panel-body
      = f.fields_for :template do |t|
        = t.hidden_field :id
        .row
          .col-sm-12
            .form-group
              = t.label :order_creation, 'Order creation (customer)'
              = t.text_area :order_creation, class: 'form-control', rows: 5
        .row
          .col-sm-12
            .form-group
              = t.label :order_update, 'Order update (customer)'
              = t.text_area :order_update, class: 'form-control', rows: 5
        .row
          .col-sm-12
            .form-group
              = t.label :order_payment, 'Order payment (owner)'
              = t.text_area :order_payment, class: 'form-control', rows: 5
        .row
          .col-sm-12
            .form-group
              = t.label :customer_creation, 'Customer creation (owner)'
              = t.text_area :customer_creation, class: 'form-control', rows: 5