config/routes.rb
KandyApp::Application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  devise_scope :user do
    namespace :users do
      scope 'manage' do
        controller :manage do
          get '/' => :index, as: 'manage'
          get '/edit/:id' => :edit, as: 'manage_edit'
          post '/edit/:id' => :update
          delete '/edit/:id' => :destroy
        end
      end
    end
  end

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  controller :home do
    get 'error' => :error
  end

  namespace :webhooks do
    scope 'sms' do
      controller :sms do
        post 'order-creation' => :order_creation
        post 'order-update' => :order_update
        post 'order-payment' => :order_payment
        # post 'order-fulfillment' => :order_fulfillment
        post 'customer-creation' => :customer_creation
      end
    end
    controller :shop do
      post 'shop/update' => :update
      end
    controller :uninstalled do
      post 'app/uninstalled' => :index
    end
  end

  scope 'preferences' do
    controller :preferences do
      get '/' => :index, as: :preferences
      get 'api-keys' => :api_keys, as: 'api_keys'
      get 'sms-alert-templates' => :sms_alert_templates, as: 'sms_alert_templates'
      get 'chat-box-widget' => :chat_box_widget, as: 'chat_box_widget'
      get 'chat-box-widget-preview' => :chat_box_widget_preview, as: 'chat_box_widget_preview'
      post '/' => :update
    end
    controller :transcripts do
      get '/transcripts' => :index, as: 'chat_transcripts'
      get '/transcripts/:id' => :view, as: 'chat_transcript'
      delete 'transcripts' => :destroy
      match 'transcripts' => :archive, via: [:put, :patch]
    end
    controller :reports do
      get '/reports' => :index
    end
  end

  scope 'help' do
    controller :help do
      get 'variables' => :variables
    end
  end

  scope 'chat' do
    controller :chat do
      post 'widget' => :widget, as: 'chat_widget'
      get 'online' => :check, as: 'chat_check_online'
      post 'online' => :ping, as: 'chat_ping_online'
      post 'change-user-status' => :change_user_status, as: 'change_user_status'
      post 'request' => :request_chat, as: 'chat_request'
      post 'join' => :join_chat, as: 'chat_join'
      post 'leave' => :leave_chat, as: 'chat_leave'
      post 'close' => :close_chat, as: 'chat_close'
      post 'save' => :save_message, as: 'chat_save'
      post 'rating' => :rating, as: 'chat_rating'
      get 'load' => :load_chat, as: 'chat_load'
      post 'send-mail' => :send_mail, as: 'chat_send_mail'
      post 'send-mail-transcript' => :send_mail_transcript, as: 'chat_send_mail_transcript'
      get 'download' => :download, as: 'chat_download'
      delete 'ban' => :ban, as: 'chat_ban'
    end
  end

  scope 'app' do
    controller :shopify do
      get 'script-tags' => :script_tags
    end
    scope 'installed' do
      controller :installed do
        get '/' => :index, as: 'app_installed'
        post 'kandy_account' => :set_kandy_account, as: 'app_installed_kandy_account'
        post 'admin_account' => :set_admin_account, as: 'app_installed_admin_account'
      end
    end
  end

  root :to => 'home#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  # GET /reports
  def index
    authorize! :read, :report

    @shop = Shop.find_by_shopify_domain(@shop_session.url)
    @conversations = @shop.conversations
    @users = @shop.users.all
  end
end

app/views/reports/index.haml
:coffeescript
  window.mainPageTitle = 'Reports'

  ShopifyApp.ready ->
    ShopifyApp.Bar.initialize
      title: window.mainPageTitle
      icon: '/icon.png'
      breadcrumb:
          label: 'Preferences'
          href: "#{preferences_path}"
          target: 'app'
      buttons:
        secondary: [
          label: 'Preferences', href: "#{preferences_url}", target: 'app'
        ]

.panel
  .panel-body
    .row.pad
      .table-responsive
        %table.table.table-hover.table-bordered#report
          %thead
            %tr.active
              %th.center{rowspan: 2} Operator
              %th.center{colspan: 6} Today
              %th.center{colspan: 6} Yesterday
              %th.center{colspan: 6} All Time
          %tbody
            %tr.active
              %td.center
                %i.fa.fa-user
              %td.center
                %i.fa.fa-comments-o
              %td.center 1
              %td.center 2
              %td.center 3
              %td.center 4
              %td.center 5
              %td.center
                %i.fa.fa-comments-o
              %td.center 1
              %td.center 2
              %td.center 3
              %td.center 4
              %td.center 5
              %td.center
                %i.fa.fa-comments-o
              %td.center 1
              %td.center 2
              %td.center 3
              %td.center 4
              %td.center 5
            - @users.each do |u|
              %tr
                %td.center= u.display_name
                %td.center= u.conversations.today.size
                %td.center= u.conversations.today.ratings(1).size
                %td.center= u.conversations.today.ratings(2).size
                %td.center= u.conversations.today.ratings(3).size
                %td.center= u.conversations.today.ratings(4).size
                %td.center= u.conversations.today.ratings(5).size
                %td.center= u.conversations.yesterday.size
                %td.center= u.conversations.yesterday.ratings(1).size
                %td.center= u.conversations.yesterday.ratings(2).size
                %td.center= u.conversations.yesterday.ratings(3).size
                %td.center= u.conversations.yesterday.ratings(4).size
                %td.center= u.conversations.yesterday.ratings(5).size
                %td.center= u.conversations.all.size
                %td.center= u.conversations.all.ratings(1).size
                %td.center= u.conversations.all.ratings(2).size
                %td.center= u.conversations.all.ratings(3).size
                %td.center= u.conversations.all.ratings(4).size
                %td.center= u.conversations.all.ratings(5).size
          %tfoot
            %tr.info
              %td.center Totals
              %td.center= @conversations.today.size
              %td.center= @conversations.today.ratings(1).size
              %td.center= @conversations.today.ratings(2).size
              %td.center= @conversations.today.ratings(3).size
              %td.center= @conversations.today.ratings(4).size
              %td.center= @conversations.today.ratings(5).size
              %td.center= @conversations.yesterday.size
              %td.center= @conversations.yesterday.ratings(1).size
              %td.center= @conversations.yesterday.ratings(2).size
              %td.center= @conversations.yesterday.ratings(3).size
              %td.center= @conversations.yesterday.ratings(4).size
              %td.center= @conversations.yesterday.ratings(5).size
              %td.center= @conversations.all.size
              %td.center= @conversations.all.ratings(1).size
              %td.center= @conversations.all.ratings(2).size
              %td.center= @conversations.all.ratings(3).size
              %td.center= @conversations.all.ratings(4).size
              %td.center= @conversations.all.ratings(5).size